// Smart CGM Raw Data
// Columns: state, team, condition, duration, endorser, month,
//          bdm, am, discount, bcaInPlan, cgmCount, cgmType, trackySensors, invoice

export const SMART_CGM_RAW = [
  ["MAHARASTRA","Field","Diabetes",1,"Dr.Anuradha desai","Jan_26","Dixit Bharat Vadher","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Inside Sales","Diabetes",1,"Self Hunt","Jan_26","Rahul Kumar Singhal","Shanta S",0,0,1,"Tracky",1,5000],
  ["TAMIL NADU","Field","Diabetes",1,"Self Hunt","Jan_26","Balaji M","Muzammil Shafique Shafique",603,0,1,"Tracky",2,9397],
  ["KARNATAKA","Field","Diabetes",1,"Dr Nagesh","Jan_26","Tausif Ahmed","Muzammil Shafique Shafique",0,0,1,"Tracky",2,10000],
  ["DELHI","Field","Diabetes",1,"Rajesh gupta","Jan_26","Swati Paliwal","Gunjan Juneja",410,0,2,"Abbott",0,10090],
  ["DELHI","Field","Diabetes",1,"Vishikant sharma","Jan_26","Swati Paliwal","Gunjan Juneja",410,0,2,"Abbott",0,10090],
  ["DELHI","Field","Diabetes",1,"Ashwani kansal","Jan_26","Lakshay Sharma","Gunjan Juneja",410,0,2,"Abbott",0,10090],
  ["DELHI","Field","Diabetes",1,"Naman Garg","Jan_26","Lakshay Sharma","Gunjan Juneja",410,0,2,"Abbott",0,10090],
  ["TAMIL NADU","Field","Diabetes",1,"Dr Sai Lakshmikanth Bharathi","Jan_26","Balaji M","Muzammil Shafique Shafique",500,0,1,"Tracky",2,9500],
  ["UTTAR PRADESH","Field","Diabetes",1,"MAYANK MISHRA","Jan_26","Saurabh Shukla","Rehan Turk",500,0,1,"Tracky",2,9500],
  ["TELANGANA","Field","Diabetes",1,"Self Hunt","Jan_26","Vinay Varshney","Shanta S",500,0,1,"Tracky",1,6000],
  ["MAHARASTRA","Field","Obesity",1,"Dr Mohammed Safwan Shaikh","Jan_26","Alfaiz Zuber Shaikh","Mohammad Gayasuddin Dasadia",500,0,1,"Tracky",2,9500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Mohammed Safwan Shaikh","Jan_26","Alfaiz Zuber Shaikh","Mohammad Gayasuddin Dasadia",500,0,1,"Tracky",2,9500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Rima Mirza","Jan_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,2,"Libre2",0,10500],
  ["UTTAR PRADESH","Field","Diabetes",1,"Dr. Nitin Ranjan Gupta","Jan_26","Anubhav Gupta","Gunjan Juneja",1000,0,1,"Tracky",2,9000],
  ["MAHARASTRA","Field","Obesity",1,"Dr Rima Mirza","Jan_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,2,"Libre2",0,11500],
  ["MAHARASTRA","Field","Obesity",1,"Shilpa Goel","Jan_26","Dixit Bharat Vadher","Rehan Turk",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Yahya Mirza","Jan_26","Alfaiz Zuber Shaikh","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Iram Shaikh","Jan_26","Sana Parkar","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Hasnain Rakhangi","Jan_26","Sana Parkar","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["DELHI","Field","Diabetes",1,"Self Hunt","Jan_26","Swati Paliwal","Gunjan Juneja",1000,0,1,"Tracky",2,8000],
  ["DELHI","Field","Diabetes",1,"Self Hunt","Jan_26","Lakshay Sharma","Gunjan Juneja",1000,0,1,"Tracky",2,8000],
  ["UTTAR PRADESH","Field","Diabetes",1,"Dr Mayank Mishra","Jan_26","Saurabh Shukla","Rehan Turk",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Yahya Mirza","Jan_26","Alfaiz Zuber Shaikh","Mohammad Gayasuddin Dasadia",0,0,2,"Libre2",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr.Rita Tari","Jan_26","Dixit Bharat Vadher","Rehan Turk",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Shweta Shrivastava","Jan_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Rima Mirza","Jan_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,2,"Tracky",3,10900],
  ["MAHARASTRA","Field","Obesity",1,"Dr Nk singh","Jan_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["BANGLORE","Marketing","Obesity",1,"Self Hunt","Jan_26","","",0,0,0,"",0,0],
  ["BANGLORE","Marketing","Obesity",1,"Self Hunt","Jan_26","","",0,0,0,"",0,0],
  ["BANGLORE","Marketing","Obesity",1,"Self Hunt","Jan_26","","",0,0,0,"",0,0],
  ["BANGLORE","Marketing","Obesity",1,"Self Hunt","Jan_26","","",0,0,0,"",0,0],
  ["UTTAR PRADESH","Field","Diabetes",1,"Dr Mayank Mishra","Jan_26","Saurabh Shukla","Rehan Turk",1000,0,2,"Tracky",2,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr.Sandeep bhandwadekar","Jan_26","Dixit Bharat Vadher","Rehan Turk",0,0,2,"",3,10900],
  ["UTTAR PRADESH","Field","Diabetes",1,"Vishal Shukla","Jan_26","Saurabh Shukla","Rehan Turk",0,0,2,"Libre2",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr.Sandeep bhandwadekar","Jan_26","Dixit Bharat Vadher","Rehan Turk",0,0,0,"Tracky",3,10900],
  ["MAHARASTRA","Field","Obesity",1,"NK Singh","Jan_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,0,"Tracky",3,10900],
  ["MAHARASTRA","Field","Obesity",1,"Dr Nk singh","Jan_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,0,"Tracky",3,10900],
  ["DELHI","Field","Obesity",1,"Faisal Malik","Jan_26","Saif Mohd","Gunjan Juneja",500,0,2,"Abbott",0,10000],
  ["DELHI","Field","Obesity",1,"Faisal Malik","Jan_26","Saif Mohd","Gunjan Juneja",500,0,2,"Abbott",0,10000],
  ["DELHI","Field","Obesity",1,"Faisal Malik","Jan_26","Saif Mohd","Gunjan Juneja",500,0,2,"Abbott",0,10000],
  ["KARNATAKA","Field","Obesity",1,"Self Hunt","Jan_26","Tausif Ahmed","Muzammil Shafique Shafique",0,0,2,"Tracky",2,10000],
  ["MAHARASTRA","Field","Obesity",1,"Dr Vinod Methil","Jan_26","Rohan Rokodoba Mortate","Rehan Turk",0,0,2,"Libre2",0,11500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Akshay Jathkar","Jan_26","Rohan Rokodoba Mortate","Rehan Turk",0,0,2,"Libre2",0,11500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Shamshunnisa","Jan_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Shamshunnisa","Jan_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Shamshunnisa","Jan_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Yahya Mirza","Jan_26","Alfaiz Zuber Shaikh","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Mohd Arbaz Farooq Qureshi","Jan_26","Alfaiz Zuber Shaikh","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Shamshunnisa","Jan_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Shamshunnisa","Jan_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",900,0,1,"Tracky",2,9100],
  ["MAHARASTRA","Field","Obesity",1,"Dr Shamshunnisa","Jan_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",900,0,1,"Tracky",2,9100],
  ["MAHARASTRA","Field","Obesity",1,"Dr Iram Shaikh","Jan_26","Sana Parkar","Mohammad Gayasuddin Dasadia",500,0,1,"Tracky",2,9500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Iram Shaikh","Jan_26","Sana Parkar","Mohammad Gayasuddin Dasadia",500,0,1,"Tracky",2,9500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Iram Shaikh","Jan_26","Sana Parkar","Mohammad Gayasuddin Dasadia",500,0,1,"Tracky",2,9500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Rima Mirza","Jan_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Rima Mirza","Jan_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["UTTAR PRADESH","Field","Diabetes",1,"Shivam Gupta","Jan_26","Saurabh Shukla","Rehan Turk",0,0,2,"Abbott",0,10500],
  ["MADHYA PRADESH","Field","Diabetes",1,"Tanya Yadav","Jan_26","Pankaj Verma","Mohammad Gayasuddin Dasadia",0,0,1,"Tracky",2,9500],
  ["MAHARASTRA","Field","Diabetes",1,"Dr Rajesh Yadav","Jan_26","Rohan Rokodoba Mortate","Rehan Turk",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Rima Mirza","Jan_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,12500],
  ["MAHARASTRA","Field","Obesity",1,"Dr.Zeenat Mullani","Jan_26","Humera Ansari","Mohammad Gayasuddin Dasadia",0,0,1,"Abbott",0,6500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Pallavi Phulpagar","Jan_26","Rohan Rokodoba Mortate","Rehan Turk",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr. Vitthal savaskar","Jan_26","Sufiyan Turk","Rehan Turk",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr. Vitthal savaskar","Jan_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Iram Shaikh","Jan_26","Sana Parkar","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Shweta Shrivastava","Jan_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,1,"Tracky",2,10900],
  ["MADHYA PRADESH","Field","Obesity",1,"Dr Vikram kapur","Jan_26","Pankaj Verma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",2,10500],
  ["MADHYA PRADESH","Field","Obesity",1,"Tanya yadav","Jan_26","Pankaj Verma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",2,10500],
  ["UTTAR PRADESH","Field","Diabetes",1,"Dr. Nitin Ranjan Gupta","Jan_26","Anubhav Gupta","Gunjan Juneja",0,0,0,"Tracky",2,8500],
  ["UTTAR PRADESH","Field","Diabetes",1,"Rajesh Pandey","Jan_26","Anubhav Gupta","Gunjan Juneja",500,0,1,"Tracky",2,9000],
  ["KARNATAKA","Field","Diabetes",1,"Khursheed Alam","Jan_26","Tausif Ahmed","Muzammil Shafique Shafique",0,0,1,"Tracky",2,10000],
  ["MAHARASTRA","Field","Obesity",1,"Dr Summit Verma","Jan_26","Saurabh Shukla","Rehan Turk",0,0,2,"Abbott",0,10500],
  ["DELHI","Field","Obesity",1,"Naseem khan","Jan_26","Saif Mohd","Gunjan Juneja",500,0,1,"Tracky",2,9000],
  ["MAHARASTRA","Field","Obesity",1,"Dr.Sandeep bhandwadekar","Jan_26","Dixit Bharat Vadher","Mohammad Gayasuddin Dasadia",1400,0,1,"Tracky",2,8100],
  ["TAMIL NADU","Field","Obesity",1,"Dr. Rajesh M","Jan_26","Joynal Abedin","Muzammil Shafique Shafique",0,0,2,"Abbott",0,10500],
  ["TAMIL NADU","Field","Obesity",1,"Dr. Azhalathithan T","Jan_26","Joynal Abedin","Muzammil Shafique Shafique",0,0,2,"Abbott",0,10500],
  ["KARNATAKA","Field","Diabetes",1,"Khursheed Alam","Jan_26","Tausif Ahmed","Muzammil Shafique Shafique",0,0,1,"Tracky",2,10000],
  ["DELHI","Field","Obesity",1,"Khursheed Alam","Jan_26","Tausif Ahmed","Muzammil Shafique Shafique",500,0,1,"Tracky",2,10000],
  ["BIHAR","Field","Obesity",1,"Khursheed Alam","Jan_26","Tausif Ahmed","Muzammil Shafique Shafique",500,0,2,"Libre2",0,11000],
  ["MAHARASTRA","Field","Obesity",1,"Dr.Sandeep bhandwadekar","Jan_26","Dixit Bharat Vadher","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr.Sandeep bhandwadekar","Jan_26","Dixit Bharat Vadher","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,12500],
  ["MAHARASTRA","Field","Obesity",1,"Shweta Shrivastava","Jan_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,11000],
  ["HARYANA","Field","Diabetes",1,"Dr. Beena Bansal","Jan_26","Nadeem Jalali","Gunjan Juneja",500,0,2,"Libre2",0,11000],
  ["DELHI","Field","Diabetes",1,"Dr. Neha","Jan_26","Nadeem Jalali","Gunjan Juneja",500,0,2,"Libre2",0,11000],
  ["HARYANA","Field","Diabetes",1,"Dr. Priyanka Gupta","Jan_26","Nadeem Jalali","Gunjan Juneja",500,0,2,"Libre2",0,11000],
  ["GUJRAT","Inside Sales","Diabetes",1,"Self Hunt","Feb_26","Rahul Kumar Singhal","Shanta S",500,0,1,"Tracky",1,6000],
  ["MAHARASTRA","Field","Obesity",1,"Shailendra Anande","Feb_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",600,0,1,"Tracky",3,11900],
  ["TAMIL NADU","Field","Obesity",1,"Sai Lakshmikanth Bharathi","Feb_26","Balaji M","Muzammil Shafique Shafique",0,0,2,"Abbott",0,10499],
  ["MAHARASTRA","Field","Obesity",1,"Dr.Sandeep bhandwadekar","Feb_26","Dixit Bharat Vadher","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["DELHI","Field","Obesity",1,"Self Hunt","Feb_26","Lakshay Sharma","Gunjan Juneja",0,0,2,"Abbott",0,10090],
  ["DELHI","Field","Obesity",1,"Rohit Juyal","Feb_26","Rajneesh Binjola","Gunjan Juneja",0,0,2,"Abbott",0,10500],
  ["KARNATAKA","Field","Diabetes",1,"Self Hunt","Feb_26","Tausif Ahmed","Muzammil Shafique Shafique",850,0,1,"Tracky",2,8650],
  ["MAHARASTRA","Field","Obesity",1,"Dr Yahya Mirza","Feb_26","Alfaiz Zuber Shaikh","Muzammil Shafique Shafique",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Yahya Mirza","Feb_26","Alfaiz Zuber Shaikh","Muzammil Shafique Shafique",0,0,2,"Abbott",0,10500],
  ["DELHI","Field","Obesity",1,"Faisal Malik","Feb_26","Saif Mohd","Gunjan Juneja",0,0,2,"Libre2",0,11500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Yahya Mirza","Feb_26","Alfaiz Zuber Shaikh","Mohammad Gayasuddin Dasadia",0,0,1,"Tracky",2,9100],
  ["HARYANA","Field","Obesity",1,"Dr Meenakshi","Feb_26","Bhawana Singh","Gunjan Juneja",0,0,2,"Abbott",0,10500],
  ["DELHI","Field","Obesity",1,"Sunil Chauhan","Feb_26","Swati Paliwal","Gunjan Juneja",410,0,2,"Abbott",0,10090],
  ["RAJASTHAN","Inside Sales","Diabetes",1,"Self Hunt","Feb_26","Komal Verma","Shanta S",1000,0,1,"Tracky",1,5000],
  ["MAHARASTRA","Field","Obesity",1,"Sandeep bhandwadekar","Feb_26","Dixit Bharat Vadher","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["KARNATAKA","Inside Sales","Diabetes",1,"Self Hunt","Feb_26","Saba Anjum","Shanta S",0,0,1,"Tracky",0,6000],
  ["DELHI","Field","Obesity",1,"Self Hunt","Feb_26","Swati Paliwal","Gunjan Juneja",410,0,2,"Abbott",0,10090],
  ["DELHI","Field","Obesity",1,"Self Hunt","Feb_26","Lakshay Sharma","Gunjan Juneja",410,0,2,"Abbott",0,10090],
  ["UTTAR PRADESH","Field","Obesity",1,"Mayank Mishra","Feb_26","Saurabh Shukla","Rehan Turk",0,0,2,"Libre2",0,11500],
  ["UTTAR PRADESH","Field","Obesity",1,"Dr Kamal","Feb_26","Bhawana Singh","Gunjan Juneja",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"N k Singh","Feb_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Shweta Shrivastava","Feb_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["DELHI","Field","Diabetes",1,"Faisal Malik","Feb_26","Saif Mohd","Gunjan Juneja",0,0,2,"Libre2",0,11500],
  ["DELHI","Field","Obesity",1,"Faisal Malik","Feb_26","Saif Mohd","Gunjan Juneja",0,0,2,"Libre2",0,11500],
  ["DELHI","Field","Obesity",1,"LATA NAGPAL","Feb_26","Sumit Bhargava","Gunjan Juneja",0,0,2,"Abbott",0,10500],
  ["DELHI","Field","Obesity",1,"ANU NAGPAL","Feb_26","Sumit Bhargava","Gunjan Juneja",0,0,2,"Abbott",0,10500],
  ["UTTAR PRADESH","Field","Diabetes",1,"Dr. Kumar Prafull Chandra","Feb_26","Anubhav Gupta","Gunjan Juneja",0,0,1,"Tracky",2,9500],
  ["HARYANA","Field","Obesity",1,"Dr Rajeeve Rajput","Feb_26","Bhawana Singh","Gunjan Juneja",0,0,2,"Abbott",0,10500],
  ["DELHI","Field","Obesity",1,"Dr. Sudhanshu","Feb_26","Swati Paliwal","Gunjan Juneja",0,0,2,"Abbott",0,10090],
  ["MAHARASTRA","Field","Obesity",1,"Dr Yahya Mirza","Feb_26","Alfaiz Zuber Shaikh","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["KARNATAKA","Field","Diabetes",1,"Lakshmi","Feb_26","Sharat CR","Muzammil Shafique Shafique",0,0,0,"Tracky",2,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Shamshunnisa","Feb_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Shamshunnisa","Feb_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["UTTAR PRADESH","Field","Obesity",1,"Dr Manoj Kumar","Feb_26","Saurabh Shukla","Rehan Turk",0,0,0,"Tracky",2,8400],
  ["DELHI","Inside Sales","Diabetes",1,"Self Hunt","Feb_26","Madhu Priya","Shanta S",500,0,1,"Tracky",1,5500],
  ["MAHARASTRA","Field","Obesity",1,"Dr.Ravindra","Feb_26","Humera Ansari","Rehan Turk",0,0,2,"Tracky",2,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Shamshunnisa","Feb_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["DELHI","Field","Obesity",1,"Dr F Haque","Feb_26","Tausif Ahmed","Muzammil Shafique Shafique",0,0,1,"Tracky",2,10000],
  ["MAHARASTRA","Field","Obesity",1,"Dr Shamshunnisa","Feb_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["UTTAR PRADESH","Field","Diabetes",1,"Self Hunt","Feb_26","Sargam Singh","Gunjan Juneja",0,0,1,"Tracky",1,6000],
  ["MAHARASTRA","Field","Obesity",1,"Shweta Shrivaatava","Feb_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MADHYA PRADESH","Field","Obesity",1,"Tanya Yadav","Feb_26","Pankaj Verma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Shweta Shrivaatava","Feb_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,0,"Tracky",3,10900],
  ["MAHARASTRA","Field","Obesity",1,"Dr Shamshunnisa","Feb_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",0,0,0,"Tracky",3,10900],
  ["MAHARASTRA","Field","Obesity",1,"Dr Shamshunnisa","Feb_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",0,0,0,"Tracky",3,10900],
  ["HARYANA","Field","Obesity",1,"Vishal Aryan","Feb_26","Sumit Bhargava","Gunjan Juneja",0,0,2,"Abbott",0,10500],
  ["HARYANA","Field","Obesity",1,"Vishal Aryan","Feb_26","Sumit Bhargava","Gunjan Juneja",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Iram Shaikh","Feb_26","Sana Parkar","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Iram Shaikh","Feb_26","Sana Parkar","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr N K Singh","Feb_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,12000],
  ["MAHARASTRA","Field","Obesity",1,"Shweta Shrivaatava","Feb_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,12000],
  ["MAHARASTRA","Field","Obesity",1,"Dr.Masiha","Feb_26","Humera Ansari","Rehan Turk",0,0,2,"Abbott",0,10500],
  ["UTTAR PRADESH","Field","Obesity",1,"Mayank Mishra","Feb_26","Saurabh Shukla","Rehan Turk",0,0,0,"Tracky",2,8400],
  ["MAHARASTRA","Field","Obesity",1,"Dr Rehmat Shaikh","Feb_26","Mohiuddin Khan","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Rima Mirza","Feb_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["UTTAR PRADESH","Field","Diabetes",1,"Nitin Ranjan Gupta","Feb_26","Anubhav Gupta","Gunjan Juneja",0,0,1,"Tracky",1,6000],
  ["MAHARASTRA","Field","Diabetes",1,"Dr. Abhishek Suryvanshi","Feb_26","Anubhav Gupta","Gunjan Juneja",0,0,1,"Tracky",1,6000],
  ["UTTAR PRADESH","Field","Diabetes",1,"Dr. Abhishek Suryvanshi","Feb_26","Anubhav Gupta","Gunjan Juneja",0,0,1,"Tracky",1,6000],
  ["UTTAR PRADESH","Field","Diabetes",1,"Abhishek Suryavanshi","Feb_26","Anubhav Gupta","Gunjan Juneja",0,0,1,"Tracky",1,6000],
  ["DELHI","Field","Obesity",1,"Kalpana Jain","Feb_26","Rajneesh Binjola","Gunjan Juneja",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Iram Shaikh","Feb_26","Sana Parkar","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Iram Shaikh","Feb_26","Sana Parkar","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr.vitthal savaskar","Feb_26","Sufiyan Turk","Rehan Turk",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Ifra Akif Shaikh","Feb_26","Alfaiz Zuber Shaikh","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MADHYA PRADESH","Field","Obesity",1,"Dr Vikalp Tiwari","Feb_26","Pankaj Verma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["UTTAR PRADESH","Field","Diabetes",1,"Abhishek Suryavanshi","Feb_26","Anubhav Gupta","Gunjan Juneja",0,0,1,"Tracky",1,6000],
  ["MADHYA PRADESH","Field","Obesity",1,"Tanya yadav","Feb_26","Pankaj Verma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MADHYA PRADESH","Field","Obesity",1,"Dr sanjay k jain","Feb_26","Pankaj Verma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["DELHI","Field","Obesity",1,"Khursheed Alam","Feb_26","Tausif Ahmed","Mohammad Gayasuddin Dasadia",0,0,1,"Tracky",2,10000],
  ["DELHI","Field","Obesity",1,"Khursheed Alam","Feb_26","Tausif Ahmed","Mohammad Gayasuddin Dasadia",0,0,1,"Tracky",2,10000],
  ["MAHARASTRA","Field","Obesity",1,"Iram Shaikh","Feb_26","Sana Parkar","Mohammad Gayasuddin Dasadia",400,0,1,"Tracky",2,9100],
  ["MAHARASTRA","Field","Obesity",1,"Sana","Feb_26","Humera Ansari","Rehan Turk",0,0,1,"Abbott",0,7800],
  ["MAHARASTRA","Field","Obesity",1,"Rima Mirza","Feb_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Iram Shaikh","Feb_26","Sana Parkar","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,11000],
  ["MAHARASTRA","Field","Obesity",1,"Rima Mirza","Feb_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["KARNATAKA","Field","Diabetes",1,"Lakshmi","Feb_26","Sharat CR","Muzammil Shafique Shafique",0,0,1,"Tracky",2,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Yahya Mirza","Feb_26","Alfaiz Zuber Shaikh","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["UTTAR PRADESH","Field","Obesity",1,"Mayank Mishra","Feb_26","Saurabh Shukla","Rehan Turk",0,0,2,"Libre2",0,11500],
  ["MADHYA PRADESH","Field","PCOS",1,"Dr Tanya yadav","Feb_26","Pankaj Verma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Yahya Mirza","Feb_26","Alfaiz Zuber Shaikh","Mohammad Gayasuddin Dasadia",0,0,0,"Tracky",3,10900],
  ["MAHARASTRA","Field","Obesity",1,"Shweta Shrivastava","Feb_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr. Maulik Koradia","Feb_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,0,"Tracky",3,10900],
  ["MADHYA PRADESH","Field","Obesity",1,"Dr Tanya","Feb_26","Pankaj Verma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Iram Shaikh","Feb_26","Sana Parkar","Mohammad Gayasuddin Dasadia",400,0,1,"Tracky",2,9100],
  ["MAHARASTRA","Field","Obesity",1,"Dr.Nisar khan","Feb_26","Sufiyan Turk","Rehan Turk",0,1,1,"Abbott",0,7500],
  ["MAHARASTRA","Field","Obesity",1,"Girish Turakia","Feb_26","Indrajeet Vishwakarma","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,11000],
  ["MAHARASTRA","Field","Obesity",1,"SANA","Feb_26","Humera Ansari","Rehan Turk",0,0,2,"Abbott",0,10500],
  ["UTTAR PRADESH","Field","Diabetes",1,"Dr. Abhishek Suryavanshi","Feb_26","Anubhav Gupta","Gunjan Juneja",0,0,1,"Tracky",2,8500],
  ["TAMIL NADU","Field","Obesity",1,"Dr. Sugumaran","Feb_26","Joynal Abedin","Muzammil Shafique Shafique",500,0,2,"Libre2",0,11000],
  ["UTTAR PRADESH","Field","Obesity",1,"Dr Rajeev Singh","Feb_26","Saurabh Shukla","Rehan Turk",400,0,1,"Tracky",2,9100],
  ["TAMIL NADU","Field","Obesity",1,"Dr. Aminul Islam","Feb_26","Joynal Abedin","Muzammil Shafique Shafique",500,0,2,"Abbott",0,10000],
  ["UTTAR PRADESH","Field","Diabetes",1,"Dr. Abhishek Suryavanshi","Feb_26","Anubhav Gupta","Gunjan Juneja",1000,0,1,"Tracky",2,8500],
  ["TAMIL NADU","Field","Obesity",1,"Dr. Karthik","Feb_26","Joynal Abedin","Muzammil Shafique Shafique",0,0,2,"Libre2",0,11000],
  ["TAMIL NADU","Inside Sales","Diabetes",1,"Self Hunt","Feb_26","Madhu Priya","Shanta S",0,0,1,"Tracky",1,5500],
  ["KARNATAKA","Field","Diabetes",1,"Praveen Ramachandra","Feb_26","Sharath C R","Muzammil Shafique Shafique",0,0,2,"Abbott",0,11500],
  ["MAHARASTRA","Field","Obesity",1,"Dr. Gazala","Feb_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,2,"Libre2",0,11500],
  ["UTTAR PRADESH","Field","Obesity",1,"Summit Verma","Feb_26","Saurabh shukla","Rehan Turk",0,0,0,"Tracky",3,10900],
  ["MAHARASTRA","Field","Obesity",1,"Dr Mohammed Safwan Shaikh","Feb_26","Alfaiz Zuber Shaikh","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["UTTAR PRADESH","Field","Diabetes",1,"Dr. Abhishek Suryavanshi","Feb_26","Anubhav Gupta","Gunjan Juneja",1000,0,1,"Tracky",2,8500],
  ["KARNATAKA","Field","Diabetes",1,"Khursheed Alam","Feb_26","Tausif Ahmed","Mohammad Gayasuddin Dasadia",0,0,1,"Tracky",2,10000],
  ["DELHI","Field","Obesity",1,"Vineeta","Feb_26","Swati Paliwal","Gunjan Juneja",410,0,2,"Abbott",0,10090],
  ["MAHARASTRA","Field","Obesity",1,"Dr Iram Shaikh","Feb_26","Sana Parkar","Mohammad Gayasuddin Dasadia",0,0,0,"Tracky",2,8100],
  ["MAHARASTRA","Field","Obesity",1,"Dr Rima Mirza","Feb_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,2,"Abbott",0,10500],
  ["KARNATAKA","Field","Obesity",1,"Lakshmi","Feb_26","Sharath C R","Muzammil Shafique Shafique",0,0,2,"Abbott",0,11500],
  ["MAHARASTRA","Field","Diabetes",1,"Dr.Nisar khan","Feb_26","Sufiyan Turk","Rehan Turk",0,0,1,"Abbott",0,6500],
  ["UTTAR PRADESH","Field","Diabetes",1,"Self Hunt","Feb_26","Sangram Singh","Gunjan Juneja",0,0,1,"Tracky",1,6000],
  ["HARYANA","Field","Diabetes",1,"Dr. Ladlee Chaterjee","Feb_26","Nadeem Jalali","Gunjan Juneja",2500,1,2,"Libre2",0,10000],
  ["HARYANA","Field","Diabetes",1,"Beena Bansal","Feb_26","Nadeem Jalali","Gunjan Juneja",2500,1,2,"Libre2",0,10000],
  ["HARYANA","Field","Obesity",1,"Meenakshi Shukla","Feb_26","Sumit Bhargava","Gunjan Juneja",0,0,2,"Abbott",0,10500],
  ["MAHARASTRA","Field","Obesity",1,"Dr Rima Mirza","Feb_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,2,"Libre2",0,11500],
  ["MAHARASTRA","Field","Obesity",1,"Abdul Rahim","Feb_26","Mohammed Rehan Meer","Mohammad Gayasuddin Dasadia",0,0,0,"Tracky",3,10900],
];
